### ISSUE TITLE
Add endpoints for creating, updating, and retrieving user information

### ISSUE THREAD

**Issue by zednis** [zednis/alexa-skill-meeting-scheduler#19]
Add endpoints for user information.  Every user should have a primary calendar.  When creating a user the user's primary calendar should be created at the same time.

**Comment by mwang25277** [comment]
Pull request created.

Copied table from DB Design document. However, I believe the primary_calendar_fk field in the User table is redundant/unnecessary. 

Create user creates a user with an autoincremented ID, and creates a Calendar for the user. ID can be changed to be taken in as another parameter if needed, but I just went with an autoincrement for now. 

Updating/Retrieving a user does not interact with calendar info. Is that correct?

Deleting a user deletes the associated calendar first, then the user itself.

Errors/status codes are same as Meeting endpoints.
